### ISSUE TITLE
[feature] Improve detection of WS3080

### ISSUE THREAD

**Issue by Nightwalker-87** [jim-easterbrook/pywws#95] opened 2020-08-29 23:05 UTC
Hi.
I am facing the same issue as #49 and can reproduce the output (https://github.com/jim-easterbrook/pywws/issues/49#issue-239193494) but with a WS3080.
However I can't find a solution to this currently but am somehow confident that this device will work either.
IMHO the hardware is very similar or even equivalent to the WH3080.
There still seems to be a problem present in the latest version.
Any help appreciated. A workaround would also be helpful.

System: Debian Bullseye (testing)
pywws-version: 20.1.0, build 1673 (92d8868) [installed via debian-repo]
Device-ID: USBDevice(0x1941, 0x8021)
Python versions: 3.8 & 3.9 (2.7 did not seem to have worked either)

See also: ad6b22fcceefb2c3209cf4ac9b2b5caa10c090a4
Note: Conversion from Python 2.x to 3.x does not seem to address encoding automatically.

**Comment by ashenshugarRET** [comment] 2020-08-30 07:23
Issue #49, seems to have been caused by trying to run pywws on Mac OS X, it was fixed by switching to ubuntu.

Can you confirm which USB library you have installed on your systems, Jim's excellent readthedocs `[documentation](https://pywws.readthedocs.io/en/latest/essentials/dependencies.html#other-systems)` recommends libusb or pyusb before trying hidapi. Have you already tried and failed with libusb and pyusb?

**Comment by Nightwalker-87** [comment] 2020-08-30 08:57
I have both
- libusb-0.1-4 (2020.01.19-1) and
- libusb-1.0-0 (2:1.0.23-2)

installed which are the newest available. I'd prefer to use libusb as well.
I have no clue why pywws tries to use hidapi, that was not intended. The program just came up with it.
The packages
- python3-hid and/or
- python3-hidapi

are not even installed. I haven't tried pyusb yet though.

**Comment by jim-easterbrook** [comment] 2020-08-30 09:26
You'd need to ask the Debian packager for that. The pywws project doesn't provide packages for any particular operating system.

**Comment by jim-easterbrook** [comment] 2020-08-30 09:53
PS pywws was appearing to try and use hidapi as it couldn't find libusb.

**Comment by Nightwalker-87** [comment] 2020-08-30 10:03
> You'd need to ask the Debian packager for that. The pywws project doesn't provide packages for any particular operating system.

I have submitted a request to Debian Maintainer Thorsten Alteholz referring to this ticket.

> PS pywws was appearing to try and use hidapi as it couldn't find libusb.

Can you update the console output for this routine to make visible what is happening in the background, such as
"Detecting pyusb" --> Found / Failed
"Trying to use hidapi instead..." etc.

This would clearly help to improve the initial setup for users and help to detect missing libraries, bindings and modules.

**Closed** 2020-09-16 15:07 UTC
